Building DAG of jobs...
Updating job 0 (run_after_checkpoint).
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	875	compareMem
	1	run_after_checkpoint
	876

[Fri May 15 21:20:55 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000234880.mem, data/annotations/ENSG00000234880.mem, data/annotationsLessExon/ENSG00000234880.gtf, data/annotations/ENSG00000234880.gtf
    output: data/results/ENSG00000234880.txt
    jobid: 4350
    wildcards: gene=ENSG00000234880

[Fri May 15 21:20:55 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000183145.mem, data/annotations/ENSG00000183145.mem, data/annotationsLessExon/ENSG00000183145.gtf, data/annotations/ENSG00000183145.gtf
    output: data/results/ENSG00000183145.txt
    jobid: 3522
    wildcards: gene=ENSG00000183145

[Fri May 15 21:20:55 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000226527.mem, data/annotations/ENSG00000226527.mem, data/annotationsLessExon/ENSG00000226527.gtf, data/annotations/ENSG00000226527.gtf
    output: data/results/ENSG00000226527.txt
    jobid: 3641
    wildcards: gene=ENSG00000226527

[Fri May 15 21:20:55 2020]
rule compareMem:
    input: data/annotationsLessExon/ENSG00000229962.mem, data/annotations/ENSG00000229962.mem, data/annotationsLessExon/ENSG00000229962.gtf, data/annotations/ENSG00000229962.gtf
    output: data/results/ENSG00000229962.txt
    jobid: 3970
    wildcards: gene=ENSG00000229962

[Fri May 15 21:20:56 2020]
Error in rule compareMem:
    jobid: 3522
    output: data/results/ENSG00000183145.txt

RuleException:
CalledProcessError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpc2e_qtnj.compareMem.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Fri May 15 21:20:56 2020]
Error in rule compareMem:
    jobid: 3641
    output: data/results/ENSG00000226527.txt

RuleException:
CalledProcessError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpo2s7i77o.compareMem.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Fri May 15 21:20:56 2020]
Error in rule compareMem:
    jobid: 4350
    output: data/results/ENSG00000234880.txt

RuleException:
CalledProcessError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmp5l20uvmq.compareMem.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Fri May 15 21:20:56 2020]
Error in rule compareMem:
    jobid: 3970
    output: data/results/ENSG00000229962.txt

RuleException:
CalledProcessError in line 167 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpg04xsibd.compareMem.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 167, in __rule_compareMem
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dlcgold/stage-unimib/extra/snake/.snakemake/log/2020-05-15T212052.922544.snakemake.log
