Building DAG of jobs...
Updating job 0 (run_after_checkpoint).
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	875	removeExon
	1	run_after_checkpoint
	876

[Fri May 15 16:06:19 2020]
rule removeExon:
    input: data/annotations/ENSG00000182670.gtf, data/chr21.fa
    output: data/annotationsLessExon/ENSG00000182670.gtf
    jobid: 120
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000182670

[Fri May 15 16:06:19 2020]
rule removeExon:
    input: data/annotations/ENSG00000205726.gtf, data/chr21.fa
    output: data/annotationsLessExon/ENSG00000205726.gtf
    jobid: 286
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000205726

[Fri May 15 16:06:19 2020]
rule removeExon:
    input: data/annotations/ENSG00000215386.gtf, data/chr21.fa
    output: data/annotationsLessExon/ENSG00000215386.gtf
    jobid: 257
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000215386

[Fri May 15 16:06:19 2020]
rule removeExon:
    input: data/annotations/ENSG00000160191.gtf, data/chr21.fa
    output: data/annotationsLessExon/ENSG00000160191.gtf
    jobid: 412
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000160191

[Fri May 15 16:06:19 2020]
Error in rule removeExon:
    jobid: 412
    output: data/annotationsLessExon/ENSG00000160191.gtf

RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpphkahx43.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Fri May 15 16:06:19 2020]
Error in rule removeExon:
    jobid: 286
    output: data/annotationsLessExon/ENSG00000205726.gtf

RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpw4r0kamp.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Fri May 15 16:06:19 2020]
Error in rule removeExon:
    jobid: 120
    output: data/annotationsLessExon/ENSG00000182670.gtf

RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmp8w9m4j99.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[Fri May 15 16:06:19 2020]
Error in rule removeExon:
    jobid: 257
    output: data/annotationsLessExon/ENSG00000215386.gtf

RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpwjyohr3s.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dlcgold/stage-unimib/extra/snake/.snakemake/log/2020-05-15T160618.807515.snakemake.log
